let media =  [ 
               {
                  mediaId:11,
                  categoryId:1,
                  mediaName:"logo",
                  url:"/media/Appbackgound/logo.webp"
                } ,
                {
                  mediaId:12,
                  categoryId:1,
                  mediaName:"cloud2",
                  url:"/media/Appbackgound/cloud2.webp"
                },
                {
                  mediaId:13,
                  categoryId:1,
                  mediaName:"turtle",
                  url:"/media/Appbackgound/turtle1.webp"
                },
                {
                  mediaId:14,
                  categoryId:1,
                  mediaName:"homeBackground",
                  url:"/media/Appbackgound/marioBackground.jpeg"
                },
                {
                  mediaId:15,
                  categoryId:1,
                  mediaName:"contactUsImg",
                  url:"/media/Appbackgound/mario and Luigi1.webp"
                },
                {
                  mediaId:16,
                  categoryId:1,
                  mediaName:"signUpImg",
                  url:"/media/Appbackgound/mario.webp"
                },
                {
                  mediaId:17,
                  categoryId:1,
                  mediaName:"loginImg",
                  url:"/media/Appbackgound/mario2.webp"
                }
               ,
               {
                  mediaId:18,
                  categoryId:1,
                  mediaName:"aboutUsImg",
                  url:"/media/Appbackgound/tree.webp"
               },
               {
                  mediaId:20,
                  categoryId:2,
                  mediaName:"noIcon",
                  url:"/media/icons/noIcon.webp"
                },
                {
                  mediaId:21,
                  categoryId:2,
                  mediaName:"aboutUsIcon",
                  url:"/media/icons/aboutUsIcon.png"
                },
                {
                  mediaId:22,
                  categoryId:2,
                  mediaName:"contactIcon",
                  url:"/media/icons/contactIcon.png"
                },
                {
                  mediaId:23,
                  categoryId:2,
                  mediaName:"emailIcon",
                  url:"/media/icons/emailIcon.jpg"
                },
                {
                  mediaId:24,
                  categoryId:2,
                  mediaName:"homeIcon",
                  url:"/media/icons/homeIcon.png"
                },
                {
                  mediaId:25,
                  categoryId:2,
                  mediaName:"loginIcon",
                  url:"/media/icons/loginIcon.png"
                },
                {
                  mediaId:26,
                  categoryId:2,
                  mediaName:"messageIcon",
                  url:"/media/icons/messageIcon.jpg"
                }, 
                {
                  mediaId:27,
                  categoryId:2,
                  mediaName:"messageIcon1",
                  url:"/media/icons/messageIcon1.png"
                }, 
                {
                  mediaId:28,
                  categoryId:2,
                  mediaName:"profilIcon",
                  url:"/media/icons/profilIcon.png"
                }, 
                {
                  mediaId:29,
                  categoryId:2,
                  mediaName:"saveIcon",
                  url:"/media/icons/saveIcon.jpg"
                },
                {
                  mediaId:210,
                  categoryId:2,
                  mediaName:"sendIcon",
                  url:"/media/icons/sendIcon.png"
                },
                {
                  mediaId:211,
                  categoryId:2,
                  mediaName:"signupIcon",
                  url:"/media/icons/signupIcon.png"
                },
                {
                  mediaId:212,
                  categoryId:2,
                  mediaName:"personalDetailsIcon",
                  url:"/media/icons/personalDetailsIcon.png"
                },
              
            ]
export default media